# Generated by Django 3.2 on 2022-05-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartNo', models.CharField(db_column='item_detail_title', max_length=32, unique=True, verbose_name='产品名称')),
                ('Manufacture', models.CharField(db_column='item_detail_manufacturer_title', max_length=32, verbose_name='制造商')),
                ('Catalog', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='目录')),
                ('Description', models.CharField(db_column='item_detail_addinfo', max_length=128, verbose_name='详情')),
                ('RohsLink', models.URLField(db_column='item_availablity_env', verbose_name='环保无铅链接')),
                ('ProductionPDFLink', models.URLField(blank=True, db_column='item_availablity_pdf', default=None, verbose_name='产品详情PDF链接')),
                ('Availability', models.CharField(blank=True, db_column='item_availablity_text', default=None, max_length=32, verbose_name='产品总数量')),
                ('LowestPrice', models.CharField(blank=True, db_column='item_availablity_low_price', default=None, max_length=32, verbose_name='最低价格')),
                ('MOQ', models.IntegerField(blank=True, default=None, null=True, verbose_name='最小订购数量')),
                ('DetailLink', models.URLField(db_column='item_detail_href', verbose_name='商品详情链接')),
                ('Picture', models.URLField(db_column='item_picture', verbose_name='图片链接')),
            ],
            options={
                'verbose_name': '产品表',
                'verbose_name_plural': '产品表',
            },
        ),
    ]
