# Generated by Django 3.2 on 2022-05-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(db_column='item_detail_addinfo', max_length=512, verbose_name='详情'),
        ),
    ]
