# Generated by Django 3.2 on 2022-05-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_manufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Availability',
            field=models.CharField(blank=True, db_column='item_availablity_text', default=None, max_length=256, verbose_name='产品总数量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='LowestPrice',
            field=models.CharField(blank=True, db_column='item_availablity_low_price', default=None, max_length=128, verbose_name='最低价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Manufacture',
            field=models.CharField(db_column='item_detail_manufacturer_title', max_length=256, verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PartNo',
            field=models.CharField(db_column='item_detail_title', max_length=256, unique=True, verbose_name='产品名称'),
        ),
    ]
