# Generated by Django 3.2 on 2022-05-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220505_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PartNo',
            field=models.CharField(db_column='item_detail_title', max_length=255, unique=True, verbose_name='产品名称'),
        ),
    ]
