# Generated by Django 3.2 on 2022-05-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_product_partno'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='CustomizePrice',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='本站自定义价'),
        ),
        migrations.AlterField(
            model_name='product',
            name='LowestPrice',
            field=models.CharField(blank=True, db_column='item_availablity_low_price', default=None, max_length=128, verbose_name='原网站最低价'),
        ),
    ]
