# Generated by Django 3.2 on 2022-05-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20220506_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CustomizePrice',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='本站自定义价'),
        ),
    ]
