# Generated by Django 3.2 on 2022-05-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_product_customizeprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品信息', 'verbose_name_plural': '产品信息'},
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(db_column='item_detail_addinfo', max_length=512, verbose_name='描述'),
        ),
    ]
