# Generated by Django 3.2 on 2022-05-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0003_auto_20220403_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedtask',
            options={'verbose_name': '已完成任务', 'verbose_name_plural': '已完成任务'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '全部任务', 'verbose_name_plural': '全部任务'},
        ),
    ]
